//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/03/2018 18:58:49 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Model.Conditions
{
    public class AreasCondition
    {
        /// <summary>
        /// 名称
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// 父级id
        /// </summary>
        public int? ParentID { get; set; }

        /// <summary>
        /// 地区类型
        /// </summary>
        public AreaType? Type { get; set; }

        /// <summary>
        ///  全拼
        /// </summary>
        public string FullPinying { get; set; }

        /// <summary>
        ///  简拼
        /// </summary>
        public string ShortPinying { get; set; }

        /// <summary>
        ///  是否常用地区
        /// </summary>
        public bool? IsUsual { get; set; }
    }
}
