//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/03/2018 18:58:49 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Project.Model;
using Project.Model.Conditions;
using Project.Model.Dtos;

namespace Project.IBLL
{
    public interface IFuelConsumptionsService
    {
        /// <summary>
        /// 新增FuelConsumptions
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        int Insert(FuelConsumptions entity);

        /// <summary>
        ///     批量新增FuelConsumptions
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Insert(List<FuelConsumptions> entitys);

        /// <summary>
        /// 更新产品
        /// </summary>
        /// <returns></returns>
        bool Update(FuelConsumptions entity);

        /// <summary>
        /// 批量更新(不使用事务)
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Update(List<FuelConsumptions> entitys);

        /// <summary>
        /// 逻辑删除FuelConsumptions
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool SoftDelete(int id);

        /// <summary>
        /// 批量逻辑删除FuelConsumptions(不使用事务)
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        bool SoftDelete(List<int> ids);

        /// <summary>
        /// 判断FuelConsumptions是否存在
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool Exists(int id);

        /// <summary>
        ///     根据主键获取FuelConsumptions
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        FuelConsumptions GetByPk(int id);

        /// <summary>
        ///     根据主键获取FuelConsumptions集合
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        List<FuelConsumptions> GetList(List<int> ids);

        /// <summary>
        ///     分页方法
        /// </summary>
        /// <param name="page"></param>
        /// <param name="size"></param>
        /// <param name="sort"></param>
        /// <param name="condition"></param>
        /// <returns></returns>
        PageModel<FuelConsumptions> GetByPage(int page, int size, string sort, FuelConsumptionsCondition condition);
    }
}
