//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/21/2018 09:42:17 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Project.Model;
using Project.Model.Conditions;
using Project.Model.Dtos;

namespace Project.IBLL
{
    public interface IMenusService
    {
        /// <summary>
        /// 新增Menus
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        int Insert(Menus entity);

        /// <summary>
        ///     批量新增Menus
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Insert(List<Menus> entitys);

        /// <summary>
        /// 更新产品
        /// </summary>
        /// <returns></returns>
        bool Update(Menus entity);

        /// <summary>
        /// 批量更新(不使用事务)
        /// </summary>
        /// <param name="entitys"></param>
        /// <returns></returns>
        bool Update(List<Menus> entitys);

        /// <summary>
        /// 逻辑删除Menus
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool SoftDelete(int id);

        /// <summary>
        /// 批量逻辑删除Menus(不使用事务)
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        bool SoftDelete(List<int> ids);

        /// <summary>
        /// 判断Menus是否存在
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        bool Exists(int id);

        /// <summary>
        ///     根据主键获取Menus
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        Menus GetByPk(int id);

        /// <summary>
        ///     根据主键获取Menus集合
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        List<Menus> GetList(List<int> ids);

        /// <summary>
        ///     分页方法
        /// </summary>
        /// <param name="page"></param>
        /// <param name="size"></param>
        /// <param name="sort"></param>
        /// <param name="condition"></param>
        /// <returns></returns>
        PageModel<Menus> GetByPage(int page, int size, string sort, MenusCondition condition);
        /// <summary>
        /// 菜单查询（树形展示）
        /// </summary>
        /// <param name="appcode"></param>
        /// <returns></returns>
        List<MenusTreeDto> GetMenus(int? appcode);

        MenusTreeDto InitMenuTree(MenusTreeDto menu, List<MenusTreeDto> menus);
    }
}
