//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/03/2018 18:58:49 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using SqlSugar;
using System;

namespace Project.Model.Dtos
{
    public class AreasDto
    {

        /// <summary>
        /// Desc_New:
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        [SugarColumn(IsPrimaryKey = true, IsIdentity = true, ColumnName = "ID")]
        public int Id { get; set; }


        /// <summary>
        /// Desc_New:名称
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public string Name { get; set; }


        /// <summary>
        /// Desc_New:父级id
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public int? ParentID { get; set; }


        /// <summary>
        /// Desc_New:地区类型
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public int Type { get; set; }


        /// <summary>
        /// Desc_New:完整拼音
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public string FullPinying { get; set; }


        /// <summary>
        /// Desc_New:拼音缩写
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public string ShortPinying { get; set; }


        /// <summary>
        /// Desc_New:是否常用地区
        /// Default_New:0
        /// Nullable_New:False
        /// </summary>           
        public byte IsUsual { get; set; }

    }
}
