//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/21/2018 09:42:17 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Project.Model.Dtos
{
    public class MenusDto
    {
        /// <summary>
        /// Desc_New:主键
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public int Id { get; set; }


        /// <summary>
        /// Desc_New:系统代码
        /// Default_New:
        /// Nullable_New:False
        /// </summary>           
        public int AppCode { get; set; }


        /// <summary>
        /// Desc_New:父级菜单id
        /// Default_New:0
        /// Nullable_New:False
        /// </summary>           
        public int ParentID { get; set; }


        /// <summary>
        /// Desc_New:名称
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public string Name { get; set; }


        /// <summary>
        /// Desc_New:路由
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public string Route { get; set; }


        /// <summary>
        /// Desc_New:排序
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public int? Sort { get; set; }


        /// <summary>
        /// Desc_New:说明
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public string Notes { get; set; }


        /// <summary>
        /// Desc_New:模块需求
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public string Modules { get; set; }


        /// <summary>
        /// Desc_New:图标类
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public string IconClass { get; set; }


        /// <summary>
        /// Desc_New:链接打开方式
        /// Default_New:1
        /// Nullable_New:False
        /// </summary>           
        public int Blank { get; set; }


        /// <summary>
        /// Desc_New:相关菜单集
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public string Relative { get; set; }


        /// <summary>
        /// Desc_New:controller
        /// Default_New:
        /// Nullable_New:True
        /// </summary>           
        public string Controller { get; set; }

        /// <summary>
        ///     添加人
        /// </summary>
        public int AddUser { get; set; }

        /// <summary>
        ///     添加时间
        /// </summary>
        public DateTime AddTime { get; set; }

        /// <summary>
        ///     修改人
        /// </summary>
        public int UpdateUser { get; set; }

        /// <summary>
        ///     修改时间
        /// </summary>
        public DateTime UpdateTime { get; set; }

        public bool Marks { get; set; }
    }
}
