//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/03/2018 18:58:49 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------
using Project.Model;
using Project.Model.Conditions;
using Project.Model.Dtos;
using System.Collections.Generic;

namespace Project.IDAL
{
    public interface IAreasManage
    {
        List<Areas> GetByParameters(AreasCondition condition);

        /// <summary>
        /// 统一更新
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        bool Update(Areas entity);
        /// <summary>
        /// 根据主键获取id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        Areas GetByPk(int id);
        /// <summary>
        /// 根据地区id获取所有子地区信息
        /// </summary>
        /// <param name="parentAreaID">地区id</param>
        /// <returns></returns>
        List<Areas> GetAreasByParentAreaID(int parentAreaID);

        PageModel<Areas> GetAreasByPage(int page, int size, string sort, List<DbCondition<Areas>> condition);
    }
}

