//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/03/2018 18:58:49 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Project.IBLL;

namespace Project.WebApi.Controllers
{
    [Produces("application/json")]
    [Route("api/fuelconsumptions")]
    public class FuelConsumptionsController : Controller
    {
        private readonly IFuelConsumptionsService _fuelConsumptionsService;

        public FuelConsumptionsController(IFuelConsumptionsService fuelConsumptionsService)
        {
            _fuelConsumptionsService = fuelConsumptionsService;
        }
    }
}
