//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 05/21/2018 09:42:17 By 朱峰
//     对此文件的更改可能会导致不正确的行为，并且如果
//     文件已存在，不会覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Project.IDAL;
using Project.Model;
using Project.Model.Dtos;
using SqlSugar;

namespace Project.DAL
{
    public class MenusManage : ManageBase<Menus>,IMenusManage
    {
		public MenusManage()
		{
		}
        public List<MenusTreeDto> GetMenus(int? appcode)
        {
            var list = Db.Queryable<Menus>().WhereIF(appcode!=null, x=>x.AppCode == appcode.Value)
                .Where(x=>x.Marks == true).OrderBy(x=>x.Sort).ToList();

            return list.Select(x => Mapper.Map<MenusTreeDto>(x)).ToList();
        }
    }
}
